### ISSUE TITLE
VpcArgs not able to set CidrBlock or Tags.

### ISSUE THREAD

**Issue by Eric-Eklund** [retgits/pulumi-blogs#3]
My Idea were not able to resolve the CidrBlock or Tags creation in VpC Args.
Miss match in type.

Solved this by explicit caste to the wanted pulumi types.

```
vpcArgs := &ec2.VpcArgs{
		CidrBlock: pulumi.String(cidrBlock),
		Tags:      pulumi.ToStringMap(tags),
}
```

Maybe im missing something or that Pulumi have been updating?

**Comment by retgits** [comment]
Hi! The Pulumi team has indeed been updating their product at an amazingly awesome pace so I haven't really been able to keep this up to date. I'd be more than happy to accept a PR from you.
